// function jediAttack () {
//     // throw "Hello there";
//     // the following code will not execute
//     console.log("**lightsaber noises**");
// }

// function lucasArts () {
//     try {
//         jediAttack();
//     }
//     catch(error) {
//         // this will only run if the exception is thrown
//         console.log(error);
//     }
//     finally {
//         console.log("++Kenobi enters the stage++");
//     }
// }

// lucasArts();
// console.log("General Kenobi, you are a bold one");

// function myFunction() {
//     return "Hi";
// }

// console.log(myFunction);
// console.log(myFunction());

// const someFunction = () => {
//     return "Hello";
// }

// console.log(someFunction());